### ISSUE TITLE
Release new version (v1.0.0) of hexo-front-matter

### ISSUE THREAD

**Issue by Ryuno-Ki** [hexojs/hexo-front-matter#17]
This way https://github.com/hexojs/hexo-front-matter/commit/4dac23e13d85460d93629a50ddc76e044d945c64 can be included in hexo, so to fix https://www.npmjs.com/advisories/788

https://www.npmjs.com/package/hexo-front-matter shows 0.2.3 as latest version.

**Comment by tcrowe** [comment]
Hello @Ryuno-Ki :wave:

With 100% of these security vulnerabilities so far you'd have to attack yourself on your local machine unless you run `hexo serve` in production, which is not recommended. That would still not break the YAML. (Unless I'm mistaken)

However! 🧐 Lets see if we can get @dependabot to help us do it.

**Comment by tcrowe** [comment]
@dependabot help

**Comment by tcrowe** [comment]
@dependabot-preview help

**Comment by tcrowe** [comment]
@dependabot upgrade

**Comment by tcrowe** [comment]
I think I misunderstood. The js-yaml version was okay in the repo but it's not published. @hexojs/core I'm unsure who does the npm publish.

```
# in you hexo-front-matter directory
git pull origin master
npm version patch
npm publish
```

Or however you usually do it! And thank you.

**Comment by YoshinoriN** [comment]
@tcrowe 
Probably, you can check who can publish this package following command.

```sh
$ npm owner ls hexo-front-matter
```

I think we should brush up (e.g. DROP Node.js v6 etc...) before a new release and maybe that version will v1.0.0.  I will create [v1.0.0 milestone](https://github.com/hexojs/hexo-front-matter/milestones). But as you know I can't publish it. We have to ask someone to publish new version after brush up.

**Comment by tcrowe** [comment]
Cool, thanks @YoshinoriN ! I didn't know that trick to find the owner. 👍

**Comment by YoshinoriN** [comment]
@hexojs/core 
I think We are ready to publish v1.0.0
Someone, please publish. Thanks :)

**Comment by Ryuno-Ki** [comment]
> Hello @Ryuno-Ki wave

Hey @tcrowe,

> With 100% of these security vulnerabilities so far you'd have to attack yourself on your local machine unless you run `hexo serve` in production, which is not recommended. That would still not break the YAML. (Unless I'm mistaken)

yeah, sure. That's one of the big advantages of Static Site Generators: Less attack surface, since the site is … static :-)

However, it has a psychological effect to developers, if `npm` flags your software as „insecure”.
